services:
  web:
    build: .
    ports:
      - '3000:80'
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      APP_HOST: http://localhost:3000
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      # Use DO Spaces in prod compose to validate encrypted credentials end-to-end
      ACTIVE_STORAGE_SERVICE: do_spaces
      DISABLE_FORCE_SSL: '1'
    volumes:
      - ./config/master.key:/rails/config/master.key:ro
      - storage:/rails/storage

  worker:
    build: .
    command: bash -lc "./bin/rails db:prepare && ./bin/rails solid_queue:start"
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      APP_HOST: http://web
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      ACTIVE_STORAGE_SERVICE: do_spaces
      DISABLE_FORCE_SSL: '1'
    volumes:
      - ./config/master.key:/rails/config/master.key:ro
      - storage:/rails/storage

volumes:
  storage:
