services:
  web:
    build: .
    command: bash -lc "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      APP_HOST: http://localhost:3000
      # Uncomment to mount master key if using credentials
      # RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    depends_on:
      - worker

  worker:
    build: .
    command: bash -lc "bin/rails db:prepare && bin/rails solid_queue:start"
    environment:
      RAILS_ENV: development
      APP_HOST: http://web:3000
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle

volumes:
  bundle:
