---
secret_key_base: ''
github:
  app_id: ''
  client_id: ''
  client_secret: ''
  installation_id: ''
  webhook_secret: ''
  private_key: ''
resend:
  api_key: ''
active_record_encryption:
  primary_key: ''
  deterministic_key: ''
  key_derivation_salt: ''
do_spaces:
  endpoint: ''
  cdn_endpoint: ''
  bucket_name: ''
  region: ''
  access_key_id: ''
  secret_access_key: ''
google:
  project_id: ''
  location: ''
  api_key: ''
  application_credentials_json: ''
mission_control:
  jobs:
    http_basic: ''
    alert_email: ''
axiom:
  token: ''
  dataset: ''
otel:
  endpoint: ''
