name: CI

on:
  push:
    branches: [main, master, '**']
  pull_request:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Node dependencies (cached)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-fund --no-audit --loglevel=error
          else
            npm install --no-fund --no-audit --loglevel=error
          fi

      - name: Run CI script
        env:
          DISABLE_PARALLEL_TESTS: '1'
        run: |
          bin/ci

  docker:
    name: Docker Build & Smoke Test
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t techub:ci .

      - name: Smoke test
        run: |
          docker run --rm --entrypoint ./bin/rails techub:ci --version
